name: Espelhar branch main.

on:
  workflow_call:
    secrets:
      VR_PACKAGE_TOKEN:
        required: true
    inputs:
      BRANCH:
        required: true
        type: string

jobs:
  keep-it-up-to-date:
    name: Espelhar branch main.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VR_PACKAGE_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Verificar se a branch existe
        id: check-branch
        run: |
          BRANCH=${{ inputs.BRANCH }}

          if ! git rev-parse --verify $BRANCH; then
            # Se a branch não existir será criada
            git checkout -b $BRANCH origin/main
          fi

      - name: Atualizar a branch com a main
        id: merge-branch
        run: |
          BRANCH=${{ inputs.BRANCH }}

          git checkout $BRANCH

          # realiza o merge da main com a homolog
          git merge --ff-only origin/main 
          if git push origin $BRANCH || true;  then
            echo "branch $BRANCH atualizada com sucesso."
          else
            echo "O merge falhou devido a conflitos. Não foi feito o push."
            echo "Resolva os conflitos localmente e tente novamente!"
          fi
